# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'liban45/test-web-app'
    command: 'buildAndPush'
    Dockerfile: '**/DOCKERFILE'
    tags: 'latest'
